---

# Update Jenkins so that plugin updates don't fail
- name: Create update directory
  file: 
    path: "{{ jenkins_home }}/updates"
    state: directory
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"

- name: Download current plugin updates from Jenkins update site
  get_url:
    url: http://updates.jenkins-ci.org/update-center.json
    dest: "{{ jenkins_home}}/updates/default.json"
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    mode: 0440

- name: Remove first and last line from json file
  replace: 
    path: "{{ jenkins_home }}/updates/default.json"
    regexp: "1d;$d"

- name: Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: "present"
    timeout: 30
    updates_expiration: 86400
    url: "{{ jenkins_url }}:{{ jenkins_port }}"
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_password != ""
