---

#- name: Wait for Jenkins to start
#  uri:
#    url: ""
#  delegate_to: localhost
#  become: false
#  register: jenkins_home_content
  # Jenkins will return 503 (service unavailable) on the home page while
  # starting (the "Please wait while Jenkins is getting ready to work" page)
#  until: jenkins_home_content.status == 200
#  retries: 30
#  delay: 5

- name: Wait for Jenkins to start up
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}/login"
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 30
  delay: 5
  until: >
    'status' in jenkins_service_status and
    jenkins_service_status['status'] == 200
