- hosts: jenkins

  vars:
    jenkins_version: "2.89.2"
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "apt"
    jenkins_include_secrets: true
    jenkins_include_custom_files: false
    githubuser: "{{ gituser }}"
    githubpassword: "{{ gitpwd }}"
    
  roles:
    - { role: /tmp/ansible/sarath.jenkins }
